version: 2.1

orbs:
  node: circleci/node@0.0.9

jobs:
  build:
    docker:
      - image: circleci/node:10.13
    working_directory: ~/openzeppelin

    steps:
      - checkout

      # Install root dependencies
      - restore_cache:
          key: dependency-cache-v1-root-{{ checksum "package.json" }}
      - run:
          name: Install root dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-v1-root-{{ checksum "package.json" }}
          paths: ["./node_modules"]

      # Install client dependencies
      - restore_cache:
          key: dependency-cache-v1-client-{{ checksum "client/package.json" }}
      - run:
          name: Install client dependencies
          command: npm install
          working_directory: "./client"
      - save_cache:
          key: dependency-cache-v1-client-{{ checksum "package.json" }}
          paths: ["./client/node_modules"]

      # Test production build
      - run:
          name: Build contracts
          command: npm run build:contracts
      - run:
          name: Build application
          command: npm run build
          working_directory: "./client"
